// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'worker.dart';

void exportXmlApi({required String to, dynamic hint}) =>
    RustLib.instance.api.exportXmlApi(to: to, hint: hint);

List<Worker> getWorkers({dynamic hint}) =>
    RustLib.instance.api.getWorkers(hint: hint);

void addWorker({required Worker worker, dynamic hint}) =>
    RustLib.instance.api.addWorker(worker: worker, hint: hint);

Worker getEmptyWorker({dynamic hint}) =>
    RustLib.instance.api.getEmptyWorker(hint: hint);

void updateWorker({required Worker worker, dynamic hint}) =>
    RustLib.instance.api.updateWorker(worker: worker, hint: hint);

void removeWorkerApi({required Worker worker, dynamic hint}) =>
    RustLib.instance.api.removeWorkerApi(worker: worker, hint: hint);
