// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class Worker {
  final UuidValue id;
  String name;
  String taj;
  String taxnumber;
  String mothersname;
  String birthdate;
  String birthplace;
  String zip;
  String city;
  String street;
  bool isSelected;

  Worker({
    required this.id,
    required this.name,
    required this.taj,
    required this.taxnumber,
    required this.mothersname,
    required this.birthdate,
    required this.birthplace,
    required this.zip,
    required this.city,
    required this.street,
    required this.isSelected,
  });

  Worker cloned({dynamic hint}) => RustLib.instance.api.workerCloned(
        that: this,
      );

  bool hasValidBirthdate({dynamic hint}) =>
      RustLib.instance.api.workerHasValidBirthdate(
        that: this,
      );

  Worker setSelected({required bool to, dynamic hint}) =>
      RustLib.instance.api.workerSetSelected(
        that: this,
        to: to,
      );

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      taj.hashCode ^
      taxnumber.hashCode ^
      mothersname.hashCode ^
      birthdate.hashCode ^
      birthplace.hashCode ^
      zip.hashCode ^
      city.hashCode ^
      street.hashCode ^
      isSelected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Worker &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          taj == other.taj &&
          taxnumber == other.taxnumber &&
          mothersname == other.mothersname &&
          birthdate == other.birthdate &&
          birthplace == other.birthplace &&
          zip == other.zip &&
          city == other.city &&
          street == other.street &&
          isSelected == other.isSelected;
}
